---
language: go

go:
  - 1.3
  - tip

env:
  - KOWA_TEST_WITH_ASSETS=true
  - KOWA_TEST_WITH_ASSETS=false

services:
  - mongodb

install:
  - go get github.com/stretchr/testify
  - go get github.com/tools/godep

script:
  - make build
  - make test
