---
language: go

go:
  - 1.3
  - 1.4
  - tip

env:
  - KOWA_TEST_EMBED_ASSETS=true
  - KOWA_TEST_EMBED_ASSETS=false

services:
  - mongodb

install:
  - go get github.com/stretchr/testify
  - go get github.com/tools/godep

script:
  - make build-ci
  - make test
